**Numpy** in short numerical python is library used for scientific computation, it provides tools to work with multi dimensional arrays and matrices.

In [3]:
import numpy as np
np.__version__  #prints the version of the currently installed numpy package

'2.1.3'

In [8]:
arr = np.array([1,2,3,4,5,6])
print(type(arr))
print(arr.size) #number of elements
print(arr.ndim) #dimension of the array
print(arr.shape) #number of rows and columns
print(arr)

<class 'numpy.ndarray'>
6
1
(6,)
[1 2 3 4 5 6]


In [ ]:
arr1 = np.array(1) #0 - d array
arr2 = np.array([1,2,3,4,5]) #1d array
arr3 = np.array([[1,2,3],[4,5,6]]) #2d array
print(arr1.ndim,arr2.ndim,arr3.ndim)

0 1 2


In [16]:
#creating 5 dimensional array
arr4 = np.array([1,2,3,4], ndmin = 5)
print(arr4.ndim,arr4)

5 [[[[[1 2 3 4]]]]]


In [ ]:
arr5 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3d array
print(arr5.ndim)

#fetching different elements from the array through index
print(arr5[0,1])
print(arr5[1,0])
print(arr5[0,1,2])
print(arr5[1,1,1])

3
[4 5 6]
[7 8 9]
6
11


In [22]:
#slicing the array
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [23]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2]) # here for columns it will pick single index 2 from row 0 and row1
print(arr[0:2,1:3]) # here 0:2 is for rows and 1:3 is for columns

[3 8]
[[2 3]
 [7 8]]


In [26]:
#array operations using numpy

arr1 = np.array([[1,2],[4,5]])
arr2 = np.array([[5,6],[7,8]])
arr5 = np.concatenate((arr1,arr2),axis= 1) #over y axis, if o then over x axis combining row after row
print(arr5)

[[1 2 5 6]
 [4 5 7 8]]


In [33]:
arr5 = np.array([1,2,3,4,5])
arr6 = np.array_split(arr5,3) #splits the array into 3 parts
print(arr6)
print(arr6[0])
print(arr[1][0])

[array([1, 2]), array([3, 4]), array([5])]
[1 2]
6


**Pandas in python** 

its a library used for data manipulation and analysis. It provides data structures like DataFrames (two-dimensional labeled arrays) and Series (one-dimensional labeled arrays) that allow for efficient handling of tabular data. 

In [37]:
import pandas as pd
arr = np.array([1,2,3,4,5])
myvar = pd.Series(arr)
print(myvar)

0    1
1    2
2    3
3    4
4    5
dtype: int64


by default it assigns the index values which you can be changed

In [39]:
myvar = pd.Series(arr,index = ('a','b','c','d','e'))
print(myvar)
print(myvar['c'])

a    1
b    2
c    3
d    4
e    5
dtype: int64
3


**Dictionaries** 

 a built-in data structure in Python used to store collections of data in key-value pairs. Each key in a dictionary must be unique and immutable (e.g., strings, numbers, tuples), while values can be of any data type and can be duplicated. Dictionaries are mutable, which means they can be changed after they are created. 

In [40]:
calories = {'day1':240,'day2':350,'day3':340}
print(calories)

{'day1': 240, 'day2': 350, 'day3': 340}


In [ ]:
myvar = pd.Series(calories) #in dictionary key becomes the default index
print(myvar)

day1    240
day2    350
day3    340
dtype: int64


In [ ]:
data = {
    'calories':[340,430,230],
    'duration':[23,10,34]
}
myvar = pd.DataFrame(data)
print(myvar.iloc[[0,1]]) #uses integer-location based indexing and selection by position.

   calories  duration
0       340        23
1       430        10


In [50]:
myvar = pd.DataFrame(data,index = ['day1','day2','day3'])
print(myvar)
print(myvar.loc['day2'])#uses label-based indexing and selection.

      calories  duration
day1       340        23
day2       430        10
day3       230        34
calories    430
duration     10
Name: day2, dtype: int64


In [5]:
import pandas as pd
datapath = "../data/dm_office_sales.csv"
df = pd.read_csv(datapath)

In [6]:
df.head()

division  level of education  training level  work experience  \
0         printers        some college               2                6   
1         printers  associate's degree               2               10   
2      peripherals         high school               0                9   
3  office supplies  associate's degree               2                5   
4  office supplies         high school               1                5   

   salary   sales  
0   91684  372302  
1  119679  495660  
2   82045  320453  
3   92949  377148  
4   71280  312802

In [7]:
df.tail()

division  level of education  training level  work experience  \
995  computer hardware  associate's degree               1                1   
996  computer software  associate's degree               1                0   
997        peripherals  associate's degree               2                8   
998        peripherals  associate's degree               2                3   
999  computer hardware        some college               0                9   

     salary   sales  
995   70083  177953  
996   68648  103703  
997  108354  450011  
998   79035  330354  
999  108444  364436

In [8]:
df.shape

(1000, 6)

In [9]:
df.columns

Index(['division', 'level of education', 'training level', 'work experience',
       'salary', 'sales'],
      dtype='object')

In [ ]:
df.info()#returns general info about dataframe, including columns non-null values count, memory usage etc

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   division            1000 non-null   object
 1   level of education  1000 non-null   object
 2   training level      1000 non-null   int64 
 3   work experience     1000 non-null   int64 
 4   salary              1000 non-null   int64 
 5   sales               1000 non-null   int64 
dtypes: int64(4), object(2)
memory usage: 47.0+ KB


In [ ]:
df.describe()# returns the min, max, count, mean, median mode etc for numerical columns

training level  work experience         salary          sales
count     1000.000000       1000.00000    1000.000000    1000.000000
mean         1.262000          6.14200   90264.207000  339833.846000
std          0.925317          2.94797   17398.617174  108555.773316
min          0.000000          0.00000   41660.000000   53067.000000
25%          1.000000          4.00000   77584.000000  259257.500000
50%          1.000000          6.00000   89946.000000  338145.500000
75%          2.000000          8.00000  101834.250000  415210.250000
max          3.000000         16.00000  159148.000000  761477.000000

In [12]:
numerical_columns = [col for col in df.columns if df[col].dtype in ['int64','float64']]
categorical_columns = [col for col in df.columns if df[col].dtype == 'object']
print("numerical columns ",numerical_columns)
print("categorical columns ",categorical_columns)

numerical columns  ['training level', 'work experience', 'salary', 'sales']
categorical columns  ['division', 'level of education']
