### Numpy in python 
NumPy stands for Numerical Python and is used for handling large, multi-dimensional arrays and matrices. Unlike Python's built-in lists NumPy arrays provide efficient storage and faster processing for numerical and scientific computations. It offers functions for linear algebra and random number generation making it important for data science and machine learning.

1. **One Dimensional Array**:
A one-dimensional array is a type of linear array

In [3]:
import numpy as np
list1 = [1,2,3,4]
array = np.array(list1)

print('list',list1)
print('array',array)
print(type(list1))

print(type(array))

list [1, 2, 3, 4]
array [1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


2. **Multi-Dimensional Array**:

A Multi-Dimensional Array is an array that can store data in more than one dimension such as rows and columns. In simple terms it is a array of arrays.

In [6]:
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]
list3 = [9, 10, 11, 12]
sample_array = np.array([list1,list2,list3])
print('multi dimensional array\n',sample_array)

multi dimensional array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Parameters of a Numpy Array**

1.**Axis**: Axis of an array describes the order of the indexing into the array.

Axis 0 = one dimensional,
Axis 1 = Two dimensional,
Axis 2 = Three dimensional 

2. **Shape**: Number of elements along with each axis and is returned as a tuple.

In [7]:
sample_array = np.array([[0, 4, 2],
                       [3, 4, 5],
                       [23, 4, 5],
                       [2, 34, 5],
                       [5, 6, 7]])

print("shape of the array :",
      sample_array.shape)

shape of the array : (5, 3)


3. **Rank**: Rank of an array is simply the number of axes or dimensions it has.

4. **Data type objects (dtype)**: Data type objects (dtype) is an example of **numpy.dtype** class. It describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.

In [8]:
sample_array2 = np.array([0.2, 0.4, 2.4])
sample_array2.dtype

dtype('float64')

**Different ways of creating an array**

1. **numpy.array()**: Numpy array object in Numpy is called ndarray. We can create ndarray using this function.

    Syntax: numpy.array(parameter)

2. **numpy.fromiter()**: The fromiter() function create a new one-dimensional array from an iterable object.

    Syntax: numpy.fromiter(iterable, dtype, count=-1)

3. **numpy.arange()**: This is an inbuilt NumPy function that returns evenly spaced values within a given interval.

    Syntax:  numpy.arange( start , stop, step , dtype=None )

4. **numpy.linspace()**: This function returns evenly spaced numbers over a specified between two limits. 

    Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

5. **numpy.empty()**: This function create a new array of given shape and type without initializing value.

    Syntax: numpy.empty(shape, dtype=float, order='C')

6. **numpy.ones()**: This function is used to get a new array of given shape and type filled with ones (1).

    Syntax: numpy.ones(shape, dtype=None, order='C')

7. **numpy.zeros()**: This function is used to get a new array of given shape and type filled with zeros (0). 

    Syntax: numpy.ones(shape, dtype=None)


In [10]:
arr = np.array([3,4,5,5])
print("Array :",arr)

#formtiers
var = "hello world!"

arr = np.fromiter(var, dtype = 'U2')

print("fromiter() array :",
      arr)

#arrange
arrange = np.arange(1, 20 , 2, 
          dtype = np.float32)

print("arrage() array ",arrange)

#linspace
lins = np.linspace(3.5, 10, 3, 
            dtype = np.int32)

print('linspace array',lins)

#empty
empty = np.empty([4, 3],
         dtype = np.int32,
         order = 'f')
print('empty() array',empty)

#numpy ones

numpyone = np.ones([4, 3],
        dtype = np.int32,
        order = 'f')

print("ones() array",numpyone)

#numpy zeros
numpyzero = np.zeros([4, 3], 
         dtype = np.int32,
         order = 'f')
print("numpy zero  array ",numpyzero )

Array : [3 4 5 5]
fromiter() array : ['h' 'e' 'l' 'l' 'o' ' ' 'w' 'o' 'r' 'l' 'd' '!']
arrage() array  [ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
linspace array [ 3  6 10]
empty() array [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
ones() array [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
numpy zero  array  [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


**NumPy - Arithmetic Operations**

Arithmetic operations are used for numerical computation and we can perform them on arrays using NumPy. With NumPy we can quickly add, subtract, multiply, divide and get power of elements in an array. NumPy performs these operations even with large amounts of data.  we’ll see at the basic arithmetic functions in NumPy and show how to use them for simple calculations.

In [ ]:
'''ArithmeticErrorAddition is an arithmetic operation where the corresponding elements of two arrays are added together.
    In NumPy the addition of two arrays is done using the np.add() function.
'''
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

add_ans = np.add(a, b)
print(add_ans)

[  7  77  23 130]


In [ ]:
''' We can subtract two arrays element-wise using the np.subtract() function '''
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

sub_ans = np.subtract(a, b)
print(sub_ans)

[ 3 67  3 70]


In [ ]:
''' Multiplication in NumPy can be done element-wise using the np.multiply() function '''
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]


In [14]:
''' Division is another important operation that is performed element-wise using the np.divide() function'''
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]


In [15]:
'''exponential power - It allows us to raise each element in an array to a specified power. 
In NumPy, this can be done using the np.power() function.'''
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

pow_ans = np.power(a, b)
print(pow_ans)

[                 25          1934917632        137858491849
 1152921504606846976]


In [16]:
''' Modulus Operation
It finds the remainder when one number is divided by another. 
In NumPy, you can use the np.mod() function to calculate the modulus element-wise between two arrays.'''
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

mod_ans = np.mod(a, b)
print(mod_ans)

[ 1  2  3 10]


**NumPy Array Broadcasting**

Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different shapes without reshaping them. It automatically adjusts the smaller array to match the larger array's shape by replicating its values along the necessary dimensions. This makes element-wise operations more efficient by reducing memory usage and eliminating the need for loops. In this article, we will see how broadcasting works.

In this example, the scalar value 10 is broadcasted to match the shape of the 2D array.

In [17]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])  
scalar = 10  

result = array_2d + scalar
print(result)

[[11 12 13]
 [14 15 16]]


**Working of Broadcasting in NumPy**
Broadcasting applies specific rules to find whether two arrays can be aligned for operations or not that are:

* **Check Dimensions**: Ensure the arrays have the same number of dimensions or expandable dimensions.
* **Dimension Padding**: If arrays have different numbers of dimensions the smaller array is left-padded with ones.
* **Shape Compatibility**: Two dimensions are compatible if they are equal or one of them is 1.

If these conditions aren’t met NumPy will raise a ValueError.

In [18]:
#broad casting 1d array to 2d array
a1 = np.array([2, 4, 6])
a2 = np.array([[1, 3, 5], [7, 9, 11]])
res = a1 + a2
print(res)

[[ 3  7 11]
 [ 9 13 17]]


In [20]:
''' broadcasting in conditional operations'''
import numpy as np

ages = np.array([12, 24, 35, 5, 60, 72])

age_group = np.array(["Adult", "Minor"])

result = np.where(ages > 18, age_group[0], age_group[1])

print(result)

['Minor' 'Adult' 'Adult' 'Minor' 'Adult' 'Adult']


In [22]:
''' Using Broadcasting for Matrix Multiplication'''
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])
result = matrix * vector
print(result)

[[10 40]
 [30 80]]


Consider a real-world scenario where we need to calculate the total calories in foods based on the amount of fats, proteins and carbohydrates. Each nutrient has a specific caloric value per gram.

* Fats: 9 calories per gram (CPG)
* Proteins: 4 CPG
* Carbohydrates: 4 CPG



In [23]:
import numpy as np
#the original data with food items and their respective grams of fats, proteins and carbs.
food_data = np.array([[0.8, 2.9, 3.9], 
                      [52.4, 23.6, 36.5],
                      [55.2, 31.7, 23.9],
                      [14.4, 11, 4.9]])
#the caloric values per gram for fats, proteins and carbs respectively
caloric_values = np.array([9,4,4]) 

caloric_matrix = caloric_values 

calorie_breakdown = food_data * caloric_matrix
print(calorie_breakdown)

[[  7.2  11.6  15.6]
 [471.6  94.4 146. ]
 [496.8 126.8  95.6]
 [129.6  44.   19.6]]


The caloric values per gram are broadcasted across each row of the food data allowing us to find the calorie breakdown efficiently.

Example 2:

Suppose you have a 2D array representing daily temperature readings across multiple cities and you want to apply a correction factor to each city’s temperature data.

In [24]:
temperatures = np.array([
    [30, 32, 34, 33, 31],  
    [25, 27, 29, 28, 26], 
    [20, 22, 24, 23, 21]  
])

corrections = np.array([1.5, -0.5, 2.0])

adjusted_temperatures = temperatures + corrections[:, np.newaxis]
print(adjusted_temperatures)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


The correction factors for each city are broadcasted to match the shape of the temperatures array.

**Normalizing Image Data**

Normalization is important in many real-world scenarios like image processing and machine learning because it:

* Centers data by subtracting the mean by ensuring features have zero mean.
* Scales data by dividing by the standard deviation by ensuring features have unit variance.
* Improves numerical stability and performance of algorithms like gradient descent.

In [25]:
image = np.array([
    [100, 120, 130],
    [90, 110, 140],
    [80, 100, 120]
])

mean = image.mean(axis=0)   
std = image.std(axis=0)    

normalized_image = (image - mean) / std
print(normalized_image)

[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


**Centering Data in Machine Learning**

Centering data is an important step in many machine learning workflows. Broadcasting helps center the data efficiently by subtracting the mean from each feature.






In [26]:
data = np.array([
    [10, 20],
    [15, 25],
    [20, 30]
])

feature_mean = data.mean(axis=0)

centered_data = data - feature_mean
print(centered_data)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]


It allows us to subtract the mean of each feature from the corresponding values in the data helps in efficiently centering the data without needing loops.

Broadcasting in NumPy helps in efficient data manipulation which makes complex operations on arrays of different shapes both straightforward and computationally efficient.